#' Add suffix to column name
#' 
#' I think dplyr::add_count will change how they add names in 1.0.0
#' used to it would add n until it got a unique name
#' I can't find the blogpost describing the new behavior,
#' but it may be good to mirror whatever that is here.
#' For now, just recursively add suffix until a unique column is found
#'
#' @param name column name to add
#' @param suffix suffix to use
#' @param names names of data.frame in which to add new column
#'
#' @return a unique name generated by prepending suffix recursively until
#'     a unique name is found
#' @noRd
add_colname_suffix <- function(name, suffix, names){
  
  stopifnot(length(suffix) == 1)
  
  if (name %in% names) {
    name <- paste0(name, suffix)
  } else {
    return(name)
  }
  add_colname_suffix(name, suffix, names)
}

#' @param ranges ranges object from join_nearest expand_hits internal function
#'
#' @param hits  hits from distanceToNearest
#' @param colname name of column to hold distance values
#' @param suffix suffix to add to colname if exists
#'
#' @noRd
add_distance_col <- function(ranges, hits, colname = "distance", suffix = ".y"){
  UseMethod("add_distance_col")
}

#' @noRd
add_distance_col.GenomicRanges <- function(ranges, hits, colname = "distance", suffix = ".y"){
  
  if (!("distance" %in% names(mcols(hits)))) {
    stop("hits object must contain a distance column")
  }
  
  colname <- add_colname_suffix(colname, suffix, names(mcols(ranges)))
  
  mcols(ranges)[colname] <- mcols(hits)$distance
  
  return(ranges)
}

#' @noRd
add_distance_col.IRanges <- function(ranges, hits, colname = "distance", suffix = ".y"){
  
  if (!("distance" %in% names(mcols(hits)))) {
    stop("hits object must contain a distance column")
  }
  
  colname <- add_colname_suffix(colname, suffix = suffix, names(mcols(ranges)))
  
  if (is.null(mcols(ranges))){
    metadata <- DataFrame("distance" = mcols(hits)$distance)
    names(metadata) <- colname
    mcols(ranges) <- metadata
  } else {
    mcols(ranges)[colname] <- mcols(hits)$distance
  }
  return(ranges)
}